#!/bin/sh
# Provision the shared JDK + Maven toolchain used to build backend/ on the Hermes
# factory box (uid 10000 "hermes"). Idempotent: safe to re-run at any time.
#
# Why a script and not a manual install: the box has no root and no Docker daemon,
# so there is no package manager and no container fallback. Everything lands under
# /opt/data/toolchains (writable by uid 10000, on the persistent volume) and is put
# on PATH through each bot profile's ~/.profile, which the Hermes terminal env
# snapshot sources (terminal.auto_source_bashrc, default true).
#
# Change control: versions are pinned here and in docs/operations/build-toolchain.md.
# Bumping a version means updating both the version constant and its checksum.
#
# Card: t_e1bded4b
set -eu

TOOLCHAIN_ROOT=/opt/data/toolchains
DOWNLOAD_DIR="$TOOLCHAIN_ROOT/_dl"

JDK_VERSION="jdk-21.0.12.1+1"
JDK_DIR="$TOOLCHAIN_ROOT/$JDK_VERSION"
JDK_URL="https://github.com/adoptium/temurin21-binaries/releases/download/jdk-21.0.12.1%2B1/OpenJDK21U-jdk_x64_linux_hotspot_21.0.12.1_1.tar.gz"
JDK_SHA256="ce79869e1307ed8ee1e2baa86a412b1eb5b75d10a01006d788a6f968bcfaee94"

MAVEN_VERSION="3.9.16"
MAVEN_DIR="$TOOLCHAIN_ROOT/apache-maven-$MAVEN_VERSION"
MAVEN_URL="https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz"
MAVEN_SHA512="831a8591fe20c8243b1dbe7d71e3244f31d1665b0804b2e825e38cbbe5ce0cafb8338851f90780735568773e0a6cd07bbec107cda0b896b008b861075358b6f6"

# Bot profiles that build/verify the Quarkus backend. Add a profile here when a new
# factory bot needs the toolchain.
PROFILE_HOMES="devops backend-developer qa-tester architect infosec frontend-developer"
PROFILES_ROOT="${HERMES_PROFILES_ROOT:-/opt/data/profiles}"

mkdir -p "$DOWNLOAD_DIR"

# --- JDK ---------------------------------------------------------------------
if [ ! -x "$JDK_DIR/bin/java" ]; then
    echo "installing Eclipse Temurin $JDK_VERSION"
    curl -fL --retry 3 -o "$DOWNLOAD_DIR/temurin21.tar.gz" "$JDK_URL"
    echo "$JDK_SHA256  $DOWNLOAD_DIR/temurin21.tar.gz" | sha256sum -c -
    tar -xzf "$DOWNLOAD_DIR/temurin21.tar.gz" -C "$TOOLCHAIN_ROOT"
else
    echo "JDK already present: $JDK_DIR"
fi
ln -sfn "$JDK_DIR" "$TOOLCHAIN_ROOT/jdk-21"

# --- Maven -------------------------------------------------------------------
if [ ! -x "$MAVEN_DIR/bin/mvn" ]; then
    echo "installing Apache Maven $MAVEN_VERSION"
    curl -fL --retry 3 -o "$DOWNLOAD_DIR/maven.tar.gz" "$MAVEN_URL"
    curl -fsS -o "$DOWNLOAD_DIR/maven.tar.gz.sha512" "$MAVEN_URL.sha512"
    printf '%s  %s\n' "$MAVEN_SHA512" "$DOWNLOAD_DIR/maven.tar.gz" > "$DOWNLOAD_DIR/expected.sha512"
    sha512sum -c "$DOWNLOAD_DIR/expected.sha512"
    tar -xzf "$DOWNLOAD_DIR/maven.tar.gz" -C "$TOOLCHAIN_ROOT"
else
    echo "Maven already present: $MAVEN_DIR"
fi
ln -sfn "$MAVEN_DIR" "$TOOLCHAIN_ROOT/maven"

# --- Shared env bootstrap ----------------------------------------------------
cat > "$TOOLCHAIN_ROOT/env.sh" <<EOF
# Shared JDK + Maven toolchain for the Hermes factory box. Safe to source repeatedly.
# Generated by scripts/provision-toolchain.sh (card t_e1bded4b) -- edit that, not this.
export JAVA_HOME=$JDK_DIR
export M2_HOME=$MAVEN_DIR
case ":\$PATH:" in
  *":\$JAVA_HOME/bin:"*) ;;
  *) PATH="\$JAVA_HOME/bin:\$M2_HOME/bin:\$PATH" ;;
esac
export PATH
EOF

# --- Wire the bot profiles ---------------------------------------------------
for profile in $PROFILE_HOMES; do
    home="$PROFILES_ROOT/$profile/home"
    [ -d "$home" ] || continue
    wrote=""
    for rc in .profile .bashrc; do
        # Only ever add our two lines to a profile home that has no such file:
        # an existing rc is somebody else's and is left untouched.
        if [ ! -e "$home/$rc" ]; then
            printf '%s\n' "# Shared JDK + Maven toolchain for Hermes bot sessions (card t_e1bded4b)." \
                          '[ -r /opt/data/toolchains/env.sh ] && . /opt/data/toolchains/env.sh' > "$home/$rc"
            wrote="$wrote $rc"
        fi
    done
    [ -n "$wrote" ] && echo "wired$wrote for profile $profile" || echo "profile $profile already wired"
done

# --- Self-check --------------------------------------------------------------
"$JDK_DIR/bin/java" -version
JAVA_HOME="$JDK_DIR" "$MAVEN_DIR/bin/mvn" -v
echo "toolchain ready; see docs/operations/build-toolchain.md"
